language: c
sudo: required
cache: apt
os:
  - linux
services:
  - docker

env:
  - TAG=centos7_ocaml4.06.0 OS=centos:7 OPAM=1.2.2 OCAML=4.06.0+trunk ALIAS='4.06.0'
  - TAG=centos7_ocaml4.05.0 OS=centos:7 OPAM=1.2.2 OCAML=4.05.0+trunk ALIAS='4.05.0'
  - TAG=centos7_ocaml4.04.1 OS=centos:7 OPAM=1.2.2 OCAML=4.04.1       ALIAS='4.04.1 latest'
  - TAG=centos7_ocaml4.03.0 OS=centos:7 OPAM=1.2.2 OCAML=4.03.0       ALIAS='4.03.0'
matrix:
  allow_failures:
    - env: TAG=centos7_ocaml4.06.0 OS=centos:7 OPAM=1.2.2 OCAML=4.06.0+trunk ALIAS='4.06.0'

install:
  - sudo apt-get update
  - sudo apt-get install -y -q -o Dpkg::Options::="--force-confnew" docker-engine

before_script:
  - docker run -d --name postgres postgres:alpine

script:
  - bash -eu travis-ci.sh
